policy_model:
  type: SACMLP
  parameters:
    dropout: 0.0
    layer_sizes: [2, 64, 64, 1]
    state_dependent_sigma: False
    log_sigma_init: 0.

# model:
#   type: torchscript
#   parameters:
#     filename: /home/sachinbm/cpu-neko-tf/neko-gpu/examples/turb_channel/model.pt